// Transfinitte Photo Archive Dataset
// High-resolution hackathon & Launchpad imagery with instant offline local assets

const GALLERY_PHOTOS = [
  {
    id: "tf-01",
    title: "Sisterhood & Community Spirit",
    category: "Community",
    author: "Aqsa Altaf (Launchpad)",
    timestamp: "Edition 01 • Day 1",
    location: "Auditorium Concourse",
    aspect: "3:2",
    iso: "ISO 400",
    shutter: "1/320s",
    aperture: "f/2.8",
    description: "Capturing the boundless excitement and warm camaraderie at the opening check-in of the hackathon festival.",
    localUrl: "./assets/photo_01.jpg",
    url: "./assets/photo_01.jpg",
    color: "#6366f1"
  },
  {
    id: "tf-02",
    title: "The Keynote Visionary",
    category: "Keynote",
    author: "Hao Zheng (Launchpad)",
    timestamp: "Edition 02 • Inauguration",
    location: "Golden Jubilee Convention Hall",
    aspect: "3:2",
    iso: "ISO 800",
    shutter: "1/200s",
    aperture: "f/2.0",
    description: "Opening address on the horizon of autonomous intelligence and building technology that serves humanity.",
    localUrl: "./assets/photo_02.jpg",
    url: "./assets/photo_02.jpg",
    color: "#0ea5e9"
  },
  {
    id: "tf-03",
    title: "The Eureka Moment",
    category: "Breakthrough",
    author: "Ann Marie Pace (Launchpad)",
    timestamp: "Edition 03 • Midnight",
    location: "Main Coding Arena",
    aspect: "3:2",
    iso: "ISO 1600",
    shutter: "1/125s",
    aperture: "f/1.8",
    description: "A spontaneous burst of triumph as a high-frequency inference pipeline compiles cleanly after 18 hours of refactoring.",
    localUrl: "./assets/photo_03.jpg",
    url: "./assets/photo_03.jpg",
    color: "#f59e0b"
  },
  {
    id: "tf-04",
    title: "Mentorship & Family Support",
    category: "Perspectives",
    author: "Stefanie Abel Horowitz",
    timestamp: "Edition 04 • Afternoon",
    location: "Veranda Sandbox",
    aspect: "3:2",
    iso: "ISO 640",
    shutter: "1/250s",
    aperture: "f/2.4",
    description: "The heartwarming human stories behind every developer who dares to build from scratch.",
    localUrl: "./assets/photo_04.jpg",
    url: "./assets/photo_04.jpg",
    color: "#ec4899"
  },
  {
    id: "tf-05",
    title: "Street Culture & Local Heritage",
    category: "Culture",
    author: "Jessica Mendez Siqueiros",
    timestamp: "Edition 05 • Twilight",
    location: "Trichy Quadrangle",
    aspect: "3:2",
    iso: "ISO 500",
    shutter: "1/400s",
    aperture: "f/2.8",
    description: "Celebrating local flavors, midnight street treats, and timeless memories outside the hacker arena.",
    localUrl: "./assets/photo_05.jpg",
    url: "./assets/photo_05.jpg",
    color: "#10b981"
  },
  {
    id: "tf-06",
    title: "The Next Generation Architect",
    category: "Futurism",
    author: "Moxie Peng (Launchpad)",
    timestamp: "Edition 06 • Morning",
    location: "Innovation Pavilion",
    aspect: "3:2",
    iso: "ISO 320",
    shutter: "1/500s",
    aperture: "f/2.0",
    description: "Eyes raised toward the future—curiosity, wonder, and determination defining tomorrow's creators.",
    localUrl: "./assets/photo_06.jpg",
    url: "./assets/photo_06.jpg",
    color: "#06b6d4"
  },
  {
    id: "tf-07",
    title: "Main Arena // Midnight Sprint",
    category: "Hacking",
    author: "TransfiNITTe Media Cell",
    timestamp: "Oct 22, 2025 • 02:30 IST",
    location: "GJCH Main Arena Hall B",
    aspect: "3:2",
    iso: "ISO 2000",
    shutter: "1/100s",
    aperture: "f/1.4",
    description: "Over 1200 hackers in deep flow state beneath pulsing blue and green cyber neon lighting grids.",
    localUrl: "./assets/photo_07.jpg",
    url: "./assets/photo_07.jpg",
    color: "#3b82f6"
  },
  {
    id: "tf-08",
    title: "Champions Podium // Grand Finale",
    category: "Triumph",
    author: "Pranav M. & Vignesh T.",
    timestamp: "Oct 23, 2025 • 16:00 IST",
    location: "Grand Podium Stage",
    aspect: "3:2",
    iso: "ISO 400",
    shutter: "1/400s",
    aperture: "f/2.8",
    description: "The gold TransfiNITTe Cup awarded to the grand prize winners amidst confetti and standing ovations.",
    localUrl: "./assets/photo_08.jpg",
    url: "./assets/photo_08.jpg",
    color: "#eab308"
  },
  {
    id: "tf-09",
    title: "Robotics & Hardware Sandbox",
    category: "Hardware",
    author: "Robotics Council NIT Trichy",
    timestamp: "Oct 22, 2025 • 14:15 IST",
    location: "Embedded Systems Lab",
    aspect: "3:2",
    iso: "ISO 800",
    shutter: "1/640s",
    aperture: "f/2.2",
    description: "Autonomous micro-drone navigation and custom PCB soldering trials tested in real-time obstacle nets.",
    localUrl: "./assets/photo_09.jpg",
    url: "./assets/photo_09.jpg",
    color: "#14b8a6"
  },
  {
    id: "tf-10",
    title: "Laser Matrix // Central Concourse",
    category: "Atmosphere",
    author: "Devansh R. (Stage Lead)",
    timestamp: "Oct 22, 2025 • 21:00 IST",
    location: "Central Concourse",
    aspect: "3:2",
    iso: "ISO 3200",
    shutter: "1/60s",
    aperture: "f/1.4",
    description: "Volumetric cyber laser arrays casting geometric planes of light over the hackathon concourse.",
    localUrl: "./assets/photo_10.jpg",
    url: "./assets/photo_10.jpg",
    color: "#a855f7"
  },
  {
    id: "tf-11",
    title: "System Architecture & Mentorship",
    category: "Mentorship",
    author: "Corporate Engineering Guild",
    timestamp: "Oct 22, 2025 • 17:40 IST",
    location: "Cluster 3 Seminar Hall",
    aspect: "3:2",
    iso: "ISO 640",
    shutter: "1/200s",
    aperture: "f/2.5",
    description: "Industry veterans stress-testing high-availability topologies and edge-compute failure scenarios.",
    localUrl: "./assets/photo_11.jpg",
    url: "./assets/photo_11.jpg",
    color: "#6366f1"
  },
  {
    id: "tf-12",
    title: "Zero Hour Countdown // 00:00:01",
    category: "Zero Hour",
    author: "Team TransfiNITTe",
    timestamp: "Oct 23, 2025 • 08:59 IST",
    location: "Jumbotron Central Screen",
    aspect: "3:2",
    iso: "ISO 1000",
    shutter: "1/250s",
    aperture: "f/2.8",
    description: "The final seconds before git merge lockdown. Heart rates peaking across all 400 competing teams.",
    localUrl: "./assets/photo_12.jpg",
    url: "./assets/photo_12.jpg",
    color: "#f43f5e"
  }
];

if (typeof window !== 'undefined') {
  window.GALLERY_PHOTOS = GALLERY_PHOTOS;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GALLERY_PHOTOS };
}
